# 网站基本信息
title: Blair Wang's Personal Website
description: Blair Wang's self website
baseurl: "/"
url: "https://jingyiii-w.github.io/BlairWang/"

# 目录配置
source: 'docs'
destination: 'docs/_site'

# 插件
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-sitemap

# 分页配置
paginate: 5
paginate_path: "/page:num/"

# 主题
theme: jekyll-theme-primer

# Markdown 处理器
markdown: kramdown

# 排除处理的文件和目录
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# SEO 配置
jekyll_seo_tag:
  type: "website"
  author: Blair Wang

# 默认布局
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
